# Generated by Django 2.2.4 on 2019-10-04 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191001_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'entrada', 'verbose_name_plural': 'entradas'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='tittle',
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 8, 19, 50, 693519, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
